// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX4oeYoNHtUYXZzc-3oq6A7GiSrAVn4qY',
    appId: '1:177297003700:android:3b1ff87c4fa9ea506773e1',
    messagingSenderId: '177297003700',
    projectId: 'viridian-d29fa',
    storageBucket: 'viridian-d29fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPjLJmh7nSSkmZOaXerzvCQ-HfeFjpo7w',
    appId: '1:177297003700:ios:9c80ebb18a1bbf146773e1',
    messagingSenderId: '177297003700',
    projectId: 'viridian-d29fa',
    storageBucket: 'viridian-d29fa.appspot.com',
    androidClientId: '177297003700-ub3l1rjoufpuoeuloqmtgm7ua1iee8jr.apps.googleusercontent.com',
    iosClientId: '177297003700-bc646evem4166is65kl9e26fspc388e7.apps.googleusercontent.com',
    iosBundleId: 'com.conradmo.viridian',
  );
}
