// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaorbVTgQ_7kAXhDz0TOlB-Kf-UMjEfNM',
    appId: '1:26141715129:android:a674d86643d09bb1c4c968',
    messagingSenderId: '26141715129',
    projectId: 'textsync-e2f51',
    storageBucket: 'textsync-e2f51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtzj9HGNf6jUmCqVi_3kBQl-hhO-D7osk',
    appId: '1:26141715129:ios:7171893e94873b47c4c968',
    messagingSenderId: '26141715129',
    projectId: 'textsync-e2f51',
    storageBucket: 'textsync-e2f51.appspot.com',
    androidClientId: '26141715129-n13j299gu1b6vm8qtlnj14vtfs0nite1.apps.googleusercontent.com',
    iosClientId: '26141715129-6a1ho8kgpchh25m0e037tmuuhqo0pkn8.apps.googleusercontent.com',
    iosBundleId: 'com.conradmo.textsync',
  );
}
